version: '3.9'

services:
  mongo:
    restart: always
    image: mongo:latest
    container_name: study-helper-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:alpine
    container_name: study-helper-redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redisdata:/data

  bot:
    restart: always
    container_name: study-helper-bot
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    build: ./bot

volumes:
  mongodata:
  redisdata:
