name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Debugging Environment Variables
      run: |
        echo "USER: ${{ secrets.SSH_USER }}"
        echo "IP: ${{ secrets.SSH_HOST }}"
        echo "DIR: ${{ secrets.WORK_DIR }}"
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        echo "Connecting to server $USER@$IP and creating directory $DIR"
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'mkdir -p ${{ secrets.WORK_DIR }}'
        rsync -avz --exclude '.git' . ${{ secrets.SSH_USER }}@{{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}

    - name: Run docker-compose on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd ${{ secrets.WORK_DIR }} && docker compose up -d --build'

